### ISSUE TITLE
Unknown error when using "dispatch build push"

### ISSUE THREAD

**Issue by BrightSkyz** [discord/gamesdk-and-dispatch#81]
**Describe the bug**
Unknown error when using `dispatch build push` to push a build.

**Steps to reproduce**
1. Open Windows Subsystem for Linux
2. Download the latest Dispatch
3. Login
4. Run `dispatch build push [branch id] [manifest] [directory]`

**Expected behavior**
The build to get uploaded and created.

**Implementation specifics**
- OS: Ubuntu 18.04 x64
- Platform: Windows Subsystem for Linux

**Stack Backtrace**
```dispatch v1.0.0-rc3-d42fde1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0:     0x7fe3372893fb - backtrace::backtrace::libunwind::trace::h034f17449c8f06d2
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x7fe3372893fb - backtrace::backtrace::trace_unsynchronized::h88fceba984274b2d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x7fe3372893fb - std::sys_common::backtrace::_print::h113a7251db1bb0bb
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x7fe3372893fb - std::sys_common::backtrace::print::he1709f3e64aa1331
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x7fe3372893fb - std::panicking::default_hook::{{closure}}::h4c7c19a95acf509e
                               at src/libstd/panicking.rs:198
   5:     0x7fe3372890fc - std::panicking::default_hook::haf2a960f108a3f30
                               at src/libstd/panicking.rs:212
   6:     0x7fe337289b70 - std::panicking::rust_panic_with_hook::h89241749267406d1
                               at src/libstd/panicking.rs:475
   7:     0x7fe3372896f2 - std::panicking::continue_panic_fmt::h2e3cd0630ee3b20c
                               at src/libstd/panicking.rs:382
   8:     0x7fe3372895d6 - rust_begin_unwind
                               at src/libstd/panicking.rs:309
   9:     0x7fe3372ac16d - core::panicking::panic_fmt::hbd9001b67b6e597c
                               at src/libcore/panicking.rs:85
  10:     0x7fe3372ac0ac - core::panicking::panic::he483004d7e992d33
                               at src/libcore/panicking.rs:49
  11:     0x7fe3371d9678 - openssl::ssl::connector::ctx::he7250ad86014e9ff
  12:     0x7fe3371d96b4 - openssl::ssl::connector::SslConnectorBuilder::new::h1dce545fdab46f91
  13:     0x7fe3371d7a7a - native_tls::TlsConnector::builder::h809864e2f9510e10
  14:     0x7fe337162e86 - reqwest::async_impl::client::ClientBuilder::new::hb0b2cd5162e2dc00
  15:     0x7fe33715625a - reqwest::client::ClientBuilder::new::h9809e62c45f18949
  16:     0x7fe336b3d94b - sentry::transport::Transport::new::h13f53c478f72c281
  17:     0x7fe336b4404c - sentry::client::Client::with_dsn_and_options::hee2c0642cfa01803
  18:     0x7fe336ad02ab - sentry::client::init::hdbb1d7c2fc59e20a
  19:     0x7fe336aa0588 - dispatch_cli::error_utils::capture::h0c48df2c5a3cbc1b
  20:     0x7fe336a83884 - dispatch::main::hc9686b27d1db3653
  21:     0x7fe336a81bc3 - std::rt::lang_start::{{closure}}::hceb10ad19f23aabc
  22:     0x7fe337289573 - std::rt::lang_start_internal::{{closure}}::h3be3cde5d166e4dd
                               at src/libstd/rt.rs:49
  23:     0x7fe337289573 - std::panicking::try::do_call::h7b76c74d123f5ca6
                               at src/libstd/panicking.rs:294
  24:     0x7fe337293e1a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  25:     0x7fe33728a13d - std::panicking::try::hcc2d7d9a75b4b064
                               at src/libstd/panicking.rs:273
  26:     0x7fe33728a13d - std::panic::catch_unwind::h77c5e75c63053cdb
                               at src/libstd/panic.rs:388
  27:     0x7fe33728a13d - std::rt::lang_start_internal::hff2edc0b2c56ef35
                               at src/libstd/rt.rs:48
  28:     0x7fe336a84022 - main
  29:     0x7fe336221b97 - __libc_start_main
  30:     0x7fe336a7bf7a - _start
  31:                0x0 - <unknown>```

**Comment by HPaulson** [comment]
Duplicate of #18 and #65

**Comment by HPaulson** [comment]
Duplicate of #18 and #65
